### ISSUE TITLE
[Ready for QA] In Level_10, The Player does not respawn 

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#29]
Found:
In Level_10, the player does not respawn

**Repro Steps:**
1 - Open Level_10
2 - Start the Level by pressing play
3 - Be killed by something in the game

**Actual Result:**
The player dies and the game becomes extremely laggy. If left for too long completely freezes unity

**Expected Result:**
The player dies and the respawns at the spawnpoint and the game progresses like normal.

**Build:**
Commit 78
12b6387247aa8180045ae4c45ae3f264092eec34

**Comment by YuYingLiWen** [comment]
This issue has been fixed in future build.

Please reverify with Commit 80
 build : a0887909289c7f0e0680682d8385f0756a328b04
