### ISSUE TITLE
In Level_10, there are 4 spawnpoints 3 of which are not in use

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#30]
**Found:**
In Level_10, there are 4 spawnpoints 3 of which are not in use

**Repro Steps:**
1 - Open Level_10
2 - Look at the scene hierarchy
3 - Search "spawnpoint in the search bar

**Actual Result:**
There are 4  spawnpoint and only 1 is used

**Expected Result:**
There only be 1 spawnpoint or all spawnpoints be used at some point.

**Build:**
Commit 78
12b6387247aa8180045ae4c45ae3f264092eec34

![](https://i.gyazo.com/1b8d47ae8a3d43896016fe82f6419a06.png)

**Comment by YuYingLiWen** [comment]
If this is invalid, you can close it yourself haha
