### ISSUE TITLE
[Resolved] In Main_Menu, the player does not get transfered to the next scene

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#31]
**Found:**
In Main_Menu, the player does not get transfered to the next scene

**Repro Steps:**
1 - Open Game using pressing Play from the preloader scene
2 - While in the main menu jump onto either the play or credits platforms
if you chose the play platform: 3 - jump down the hole opened by the play button

**Actual Result:**
The screen goes black and nothing happens

**Expected Result:**
The player is sent to the respective level/scene

**Build:**
Commit 78
12b6387247aa8180045ae4c45ae3f264092eec34

**Comment by YuYingLiWen** [comment]
Nice find! 

Engi: Attached the scene lodader to Preloader instead of Main Menu.

Please reverify on next patch.

**Comment by YuYingLiWen** [comment]
Please verify on Commit 80
build : a0887909289c7f0e0680682d8385f0756a328b04

**Comment by Ayshie-God** [comment]
The player is now tranfered to the next scene in Commit 80
