### ISSUE TITLE
In all of the levels, the player does not respawn

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#32]
**Found:**
In all of the levels, the player does not respawn

**Repro Steps:**
1 - Open Level_1, Level_2, Level_3, etc
2 - Start the Level by pressing play
3 - Be killed by something in the game

**Actual Result:**
The player dies and nothing happens

**Expected Result:**
The player dies and the respawns at the spawnpoint and the game progresses like normal.

**Build:**
Commit 78
12b6387247aa8180045ae4c45ae3f264092eec34

**Comment by YuYingLiWen** [comment]
Closing bug as invalid. Impossible for the Player to launch levels seperately. 

Please test starting from Preloader or Build the game.
