### ISSUE TITLE
In all levels, the player does not get transfered to the next scene/level

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#33]
**Found:**
In all levels, the player does not get transfered to the next scene/level

**Repro Steps:**
1 - Open Level_1, Level_2, Level_3, etc
2 - Start the Level by pressing play
3 - Reach the teleport

**Actual Result:**
The Screen fades to black and nothing happens

**Expected Result:**
The Next Level begins allowing you to continue with the game

**Build:**
Commit 78
12b6387247aa8180045ae4c45ae3f264092eec34

**Comment by YuYingLiWen** [comment]
Closing bug as invalid. Impossible for the Player to launch levels seperately. 

Please test starting from Preloader or Build the game.
