### ISSUE TITLE
[Fixed] MainMenuScene, all of the volume slider affect the SFX rather than their respective slider

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#35]
**Found:**
In MainMenuScene, all of the volume slider affect the SFX rather than their respective group

**Repro Steps:**
1 - Start the game by pressing play from the preloaderscene
2 - Jump onto the "Settings" Platform.
3 - Move any of the sliders

**Actual Result:**
The Group affected in the audio mixer is SFX 
**Expected Result:**
The slider affect their respective group

**Build:**
Commit 80
a0887909289c7f0e0680682d8385f0756a328b04

https://imgur.com/YQk9qcc

**Comment by YuYingLiWen** [comment]
I've set the sliders to change on the correct value in Audiomixer.

Please verify in upcoming Commit 84.
build : 675b74caac0db24a2ebb069eb227e1c632c995a4
