### ISSUE TITLE
[Fixed] In MainMenuScene, the player does not get transfered to the Credits

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#36]
**Found:**
In MainMenuScene, the player does not get transfered to the Credits

**Repro Steps:**
1 - Open Game using pressing Play from the preloader scene
2 - While in the main menu jump onto the credits platform

**Actual Result:**
The screen goes black and nothing happens

**Expected Result:**
The player is sent to the credits scene

**Build:**
Commit 80
a0887909289c7f0e0680682d8385f0756a328b04

https://gyazo.com/38b878ddb8b0b931005e0a70c57cd592

**Comment by YuYingLiWen** [comment]
Issue was caused by a previous bug fix. Should be good to go now ;)

Please verify on Commit 84.
build : 675b74caac0db24a2ebb069eb227e1c632c995a4
