### ISSUE TITLE
[Fixed] In any scene, after touching a wall the player will flicker as if they're are jumping

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#37]
**Found:**
In any scene, after touching a wall the player will flicker as if they're in jumping when only moving on the ground

**Repro Steps:**
1 - Open Game using pressing Play from the preloader scene
2 - Reach a scene with walls
3 - Touch a wall
4 - Move around

**Actual Result:**
The player flickers and becomes invisible when standing still, issue stops upon jumping

**Expected Result:**
The player be visible while simply walking/running

**Build:**
Commit 80
a088790

https://gyazo.com/39f5f1b37c75651a9d0262811b4af40e

**Comment by YuYingLiWen** [comment]
I've adjusted the script to take account how many surface the player has made contact with so the player will remain visible during lateral movements after hitting a exiting from a second wall.

Please verify on Commit 84.
build : 675b74caac0db24a2ebb069eb227e1c632c995a4
