### ISSUE TITLE
In Level 4 and Level_5, the player's movement becomes delayed and or unusable

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#42]
Found:
In Level 4 and Level_5, the player's movement becomes delayed and or unusable
Repro Steps:
1 - Open Game using pressing Play from the preloader scene
2 - Reach Level_4 or Level_5
3 - Build up momentum in one of the direction
4 - Try to jump or change direction

Actual Result:
The Players will only jump about 1-2 seconds later, or not at all
In Level_5 while running towards the end the player cannot jump or change direction and even after releasing the button the player will not slow down, which makes the level unbeatable due to inability to dodge last obstacle

Expected Result:
The player jumps using the momentum or slows down changing movement Direction

Build:
Commit 84
675b74caac0db24a2ebb069eb227e1c632c995a4

**Comment by YuYingLiWen** [comment]
Level 5
![Level 5](https://user-images.githubusercontent.com/38596161/79079358-93a5fe00-7cdc-11ea-853a-3b05014793a3.gif)

**Comment by Ayshie-God** [comment]
some issue might be happening with my editor/laptop because sometimes it's fine and other times it won't let me me jump or slow down my momentum

**Comment by YuYingLiWen** [comment]
9.9MB made it!!!! Anyway here is level 4. I cut some parts off because GitHub only allows file < 10MB
![Level 4 3](https://user-images.githubusercontent.com/38596161/79079559-e7fdad80-7cdd-11ea-813b-0ee6795eb524.gif)

**Comment by YuYingLiWen** [comment]
Gonna flag it as nmi(Need more Information) for now.

**Comment by YuYingLiWen** [comment]
Also the player is always slighty ahead. By 0.9 seconds to be precise of its previous position shown on the screen when jumping. Not sure if this is what you are experiencing

**Comment by Ayshie-God** [comment]
What I'm experience is while I move to the horizontally upon reaching the point I should slowdown and jump after holding it down so I keep moving ahead but after releasing the button I keep moving as if I'm still holding it down and become unable to jump. I'll try to get a video of it next time it happens though I'll need to find a way to show my inputs so you can get the full picture. It was happening pretty often earlier today but after restarting my laptop it hasn't happened yet so I'll try putting it on my desktop and seeing if it is simply an issue with my laptop or a bug that happens randomly

**Comment by Ayshie-God** [comment]
issue seems not to be appearing anymore so I'm gonna close this issue unless it shows up again
