### ISSUE TITLE
In Level_6, the player can't seem to hit the teleport

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#43]
**Found:**
In Level_6, the player can't seem to hit the teleport
Repro Steps:
1 - Open Game using pressing Play from the preloader scene
2- reach Level 6
3 - Go down the correct path

**Actual Result:**
The player misses the teleport and dies

**Expected Result:**
The Player is launched at the teleport sending them to the next level, or the player is launched towards the teleport needing to do adjustment to actually reach it

**Build:**
Commit 84
675b74caac0db24a2ebb069eb227e1c632c995a4

**Comment by YuYingLiWen** [comment]
Intended and closing as invalid. Try harder XD
