### ISSUE TITLE
[Ready for QA] In Level_7, the player can get stuck in an infinite death screen

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#54]
Repro
Start game from preloader
Reach Level 7
touch the yellow circle
fall into the spikes

Actual Result
 the player dies, the death screen appears and simply stays there while the death sound can be heard constantly playing

Expected Result
The player dies, the death screen appears, the player respawns, and the game goes on normally.

**Comment by YuYingLiWen** [comment]
Issue has been fixed on future patch. Player Death "should" not be able to crash the game in the majority of cases.
