### ISSUE TITLE
[Ready for QA] Beating Level_5 leads to Level_7

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#55]
Repro
Play game from preloader
Reach Level_5
Reach teleporter

Actual Result
Get sent to Level_7

Expected Result
Get sent to Level_6

**Comment by YuYingLiWen** [comment]
The way how the backend function in future build will be very diffrent from the build you've tested on. 

Please reverify the gameflow in next patch.
