### ISSUE TITLE
[Ready for QA] In A1 the player is not sent to next scene

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#56]
Repro 
Start game from preloader
Reach A1
Reach the teleporter

Actual Result 
nothing happens

Expected Result
Get sent to the next level

**Comment by YuYingLiWen** [comment]
The way how the backend function in future build will be very diffrent from the build you've tested on.

Please reverify the gameflow in next patch.

**Comment by Ayshie-God** [comment]
the player is new sent to the next scene but instead of the next level it is the main menu

**Comment by YuYingLiWen** [comment]
Issue fixed in commit 102

please reverfiy
