### ISSUE TITLE
[Ready for QA] In Level_7 there's no way to leave (other than dying to yellow circle spikes)

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#57]
Repro
Reach Level_7
try touching any of the circles (other than yellow)

Actual result
I'm stuck in the box with no exit, other than dying to yellow circle spikes.

Expected result
I can leave the box and progres

**Comment by YuYingLiWen** [comment]
Issue has been fixed on future build.

**Comment by YuYingLiWen** [comment]
Reopening the Issue. Issue occurs the same way as described.

Edit: The Yellow dots should be 1 for the trigger. The rest of the dots should also be triggers however they are currently inactive when collided with.

**Comment by Ayshie-God** [comment]
ahh I see I waited for the timer to run out to run out and the box dissapeared so I assumed that's what was intened

**Comment by YuYingLiWen** [comment]
Yup, it does look intended, since there are not design documents explaining about it except in my head, so its normal that you don't know haha. Issue has been fixed on Commit 102.

Please reverfiy.
