### ISSUE TITLE
[Ready for QA] In Main Menu, the player will fall through floor when jumping onto platform teleporter

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#60]
Repro
Reach main menu
Jump onto play platform teleporter

actual result
the player falls through while being transfered to next scene

expected result
the player sits there as scene fades out to new scene

**Comment by YuYingLiWen** [comment]
Fixed on Commit 102. Player will not be able to penetrate walls after reaching a teleporter.

Please reverify.
