### ISSUE TITLE
In A1 the player does not respawn

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#61]
Repro
Reach A1
die

Actual result
player dies, death screen appears, death screen dispeares and camera simply shows where the player died, no new player spawns

Expected
Die, respawn, and progress with no issue

**Comment by YuYingLiWen** [comment]
Can you attach a gif or image to illustrate your issue? Thank you!

**Comment by Ayshie-God** [comment]
https://imgur.com/ZpMPvXx 
here's a video to show what I mean

**Comment by YuYingLiWen** [comment]
Will fix when I have the time

**Comment by YuYingLiWen** [comment]
Closing as Known shippable.
