### ISSUE TITLE
[ready for qa]Timer infinitely paused in Level_7

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#67]
Repro
Reach Level 7
pause game
unpause game

Actual Result
Timer stops counting down after unpausing

Expected Result
The timer continues to count down after unpausing

Commit 105
200e9b22db1d59ca199d1dd53338f6874b24bd15

**Comment by YuYingLiWen** [comment]
Issue has been in fied on commit 106
