### ISSUE TITLE
player can get stuck in infinie death loop on Level 7

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#68]
Repro
Reach Level 7
Touch one of the dots

Note
This bug occurs typically when touching the yellow or red ball, but occurs on all other balls too sometimes

Actual Result
The player gets locked in infinite death

Expected Result
The player respawns and moves on

Commit 105
200e9b22db1d59ca199d1dd53338f6874b24bd15

https://imgur.com/7PJZPHS

**Comment by YuYingLiWen** [comment]
I tried to fix this thing. it is cancer. Now it is "good" but I can't tell what happens on the other level. On Level 7 it is good.

**Comment by YuYingLiWen** [comment]
Closing as fixed since i didn't get stuck while playing the entire game.
